from google.adk.agents import Agent

from config import get_settings

# Code Reviewer Agent
# Takes the code generated by the previous agent (read from state) and provides feedback.
code_reviewer_agent = None
try:
    code_reviewer_agent = Agent(
        model=get_settings().MODEL_GEMINI_2_0_FLASH,
        name="code_reviewer_agent",
        instruction="""You are an expert Python Code Reviewer. 
    Your task is to provide constructive feedback on the provided code.

    **Code to Review:**
    ```python
    {generated_code}
    ```

**Review Criteria:**
1.  **Correctness:** Does the code work as intended? Are there logic errors?
2.  **Readability:** Is the code clear and easy to understand? Follows PEP 8 style guidelines?
3.  **Efficiency:** Is the code reasonably efficient? Any obvious performance bottlenecks?
4.  **Edge Cases:** Does the code handle potential edge cases or invalid inputs gracefully?
5.  **Best Practices:** Does the code follow common Python best practices?

**Output:**
Provide your feedback as a concise, bulleted list. Focus on the most important points for improvement.
If the code is excellent and requires no changes, simply state: "No major issues found."
Output *only* the review comments or the "No major issues" statement.
""",
        description="Reviews code and provides feedback.",
        output_key="review_comments",  # Stores output in state['review_comments']
    )

    print(
        f"✅ Agent '{code_reviewer_agent.name}' created using model '{code_reviewer_agent.model}'."
    )
except Exception as e:
    print(f"❌ Could not create Code Reviewer agent. Error: {e}")
